version: '3.7'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    restart: always
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=my_cluster
    ports:
      - "9042:9042"
      - "9160:9160"
    # volumes:
    #   - ./data/cassandra1:/var/lib/cassandra

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    restart: always
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=my_cluster
    # volumes:
    #   - ./data/cassandra2:/var/lib/cassandra

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    restart: always
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=my_cluster
    # volumes:
    #   - ./data/cassandra3:/var/lib/cassandra
