---
version: "3"

#volumes:
  #db:
  # logs:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:${MONGODB_PORT}/

  srv:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: 0xb1b1/rlt-hack-backend:latest
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "logs:/data"
    # depends_on:
    #   - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rlt-hack-backend.loadbalancer.server.port=80"
      - "traefik.http.routers.rlt-hack-backend.rule=Host(`rlt-backend.seizure.icu`)"
      - "traefik.http.routers.rlt-hack-backend.entrypoints=websecure"
      - "traefik.http.routers.rlt-hack-backend.tls=true"
